### ISSUE TITLE
WmWare 

### ISSUE THREAD

**Issue by Andrej123456789** [ilobilo/kernel#2]
I "burn" iso image in WmWare Vorkstation 16 and display blue "window" and then WmWare display error about Virtual CPU and restart WmWare.

**Comment by ilobilo** [comment]
I don't think that's kernel issue

**Comment by Andrej123456789** [comment]
It's not kernel issue,, but do you know how to directly mount ISO image to Qemu

**Comment by ilobilo** [comment]
Please ask on discord server
