### ISSUE TITLE
error: invalid combination of opcode and operands

### ISSUE THREAD

**Issue by fgsoftware1** [ilobilo/kernel#25]
`
...(sucefully until here)
ASM     source/system/cpu/syscall/syscall.asm
/root/kernel/source/system/cpu/syscall/syscall.asm:12: warning: register size specification ignored [-w+other]
/root/kernel/source/system/cpu/syscall/syscall.asm:7: error: invalid combination of opcode and operands
/root/kernel/source/system/cpu/syscall/syscall.asm:8: error: invalid combination of opcode and operands
/root/kernel/source/system/cpu/syscall/syscall.asm:12: error: invalid combination of opcode and operands
make[2]: *** [Makefile:160: /root/kernel/source/system/cpu/syscall/syscall_asm.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:139: /root/kernel/source/kernel.elf] Error 2
make: *** [Makefile:10: bios] Error 2
`

**Comment by ilobilo** [comment]
Try changing lines 7 and 8 in syscall.asm to this and tell me if it still fails to compile
```asm
mov qword gs:[8], rsp
mov rsp, qword gs:[16]
```

**Comment by fgsoftware1** [comment]
> Try changing lines 7 and 8 in syscall.asm to this and tell me if it still fails to compile
> 
> ```assembly
> mov qword gs:[8], rsp
> mov rsp, qword gs:[16]
> ```

`
/root/kernel/source/system/cpu/syscall/syscall.asm:7: warning: register size specification ignored [-w+other]
/root/kernel/source/system/cpu/syscall/syscall.asm:8: warning: register size specification ignored [-w+other]
/root/kernel/source/system/cpu/syscall/syscall.asm:12: warning: register size specification ignored [-w+other]
/root/kernel/source/system/cpu/syscall/syscall.asm:7: error: invalid combination of opcode and operands
/root/kernel/source/system/cpu/syscall/syscall.asm:8: error: invalid combination of opcode and operands
/root/kernel/source/system/cpu/syscall/syscall.asm:12: error: invalid combination of opcode and operands
make[2]: *** [Makefile:160: /root/kernel/source/system/cpu/syscall/syscall_asm.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:139: /root/kernel/source/kernel.elf] Error 2
make: *** [Makefile:6: all] Error 2
`

**Comment by ilobilo** [comment]
it works on my machine
what os are you using?

**Comment by fgsoftware1** [comment]
> it works on my machine what os are you using?

wsl

**Comment by ilobilo** [comment]
wsl2 with ubuntu 20.04?

**Comment by fgsoftware1** [comment]
> wsl2 with ubuntu 20.04?

yes

**Comment by fgsoftware1** [comment]
@ilobilo still same on ubuntu 20.04

**Comment by ilobilo** [comment]
Well I use 21.10
20.04 has older packages

**Comment by fgsoftware1** [comment]
> Well I use 21.10 20.04 has older packages

on your machine or VM/container

**Comment by ilobilo** [comment]
on my machine
its my main os
