### ISSUE TITLE
Pink colour

### ISSUE THREAD

**Issue by Andrej123456789** [ilobilo/kernel#3]
Add other colour on right click of mouse

**Comment by ilobilo** [comment]
What colour?

**Comment by Andrej123456789** [comment]
Something what isn't pink and purple

**Comment by Andrej123456789** [comment]
Add WmWare supprot in near future

**Comment by ilobilo** [comment]
It has VMware support

**Comment by Andrej123456789** [comment]
It doesn't work for me. See my first issue on this repo

**Comment by Andrej123456789** [comment]
And change color

**Comment by ilobilo** [comment]
Ok
